# Connect Notify - Discord notifications for your Minecraft server
# https://github.com/minekube/connect-notify

discord:
  # Add your Discord webhook URL(s) here
  # Create one: Right-click channel > Edit Channel > Integrations > Webhooks
  webhooks:
    - ''

  # Bot appearance
  username: 'Connect Notify'
  avatar-url: 'https://github.com/minekube.png'

# Enable/disable notifications
notifications:
  online: true
  offline: true
